### ISSUE TITLE
ERROR Plugin load failed: hexo-lightning-minify

### ISSUE THREAD

**Issue by FidStyle** [theme-shoka-x/hexo-lightning-minify#5]
在每次hexo ( `hexo`、`hexo --version`、`hexo cl`、`hexo g`、`hexo s` ) 命令运行都会重复出现重复段代码
```bash
ERROR Plugin load failed: hexo-lightning-minify
TypeError: Cannot set properties of undefined (setting 'js')
    at D:\Users\fid\Desktop\hexo7+npm+shokaX\node_modules\hexo-lightning-minify\index.js:7:23
    at D:\Users\fid\Desktop\hexo7+npm+shokaX\node_modules\hexo\dist\hexo\index.js:248:20
    at tryCatcher (D:\Users\fid\Desktop\hexo7+npm+shokaX\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Users\fid\Desktop\hexo7+npm+shokaX\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\Users\fid\Desktop\hexo7+npm+shokaX\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\Users\fid\Desktop\hexo7+npm+shokaX\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\Users\fid\Desktop\hexo7+npm+shokaX\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\Users\fid\Desktop\hexo7+npm+shokaX\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\Users\fid\Desktop\hexo7+npm+shokaX\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\Users\fid\Desktop\hexo7+npm+shokaX\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (D:\Users\fid\Desktop\hexo7+npm+shokaX\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
```

具体见[hexo-theme-shokaX/issues](https://github.com/theme-shoka-x/hexo-theme-shokaX/issues/194)

@zkz098

**Comment by FidStyle** [comment]
@zkz098

**Comment by FidStyle** [comment]
@D-Sketon

**Comment by D-Sketon** [comment]
是否在 `_config.yml` 中进行了 `hexo-lightning-minify` 的配置？

**Comment by FidStyle** [comment]
取消注释好了，没注意。谢谢了

**Comment by MoYuYuDe** [comment]
> 取消注释好了，没注意。谢谢了

请问是取消哪里的注释啊? 我检查了 `_config.yml` 文件, 里面也没有关于 `hexo-lightning-minify` 的配置

**Comment by FidStyle** [comment]
> > 取消注释好了，没注意。谢谢了
> 
> 请问是取消哪里的注释啊? 我检查了 `_config.yml` 文件, 里面也没有关于 `hexo-lightning-minify` 的配置

进入node_module/hexo-theme-shokax，找到_config.yml，复制到根目录并重命名为_config.shokaX.yml，里面是模版

**Comment by FidStyle** [comment]
@zkz098 文档好像没写这部分的内容
原文描述是
> 更改根目录 /_config.yml 中的 theme 为 shokaX (SXC 默认 origin 或 npm 安装修改为 shokax)
> 请注意，本主题仅在 npm 上使用的是shokax,其他情况下均为shokaX
> 对于 linux 等大小写敏感的系统，npm 源的 theme 必须使用shokax同时修改自定义配置文件为_config.shokax.yml

没有说明_config.shokax.yml的来源

**Comment by zkz098** [comment]
> > 取消注释好了，没注意。谢谢了
> 
> 请问是取消哪里的注释啊? 我检查了 `_config.yml` 文件, 里面也没有关于 `hexo-lightning-minify` 的配置

实际上配置在 https://docs.kaitaku.xyz/guide/config.html#%E6%96%87%E4%BB%B6%E5%8E%8B%E7%BC%A9
或者本项目README内也有配置模板，填入hexo根目录的_config.yml即可

**Comment by zkz098** [comment]
> @zkz098 文档好像没写这部分的内容 原文描述是
> 
> > 更改根目录 /_config.yml 中的 theme 为 shokaX (SXC 默认 origin 或 npm 安装修改为 shokax)
> > 请注意，本主题仅在 npm 上使用的是shokax,其他情况下均为shokaX
> > 对于 linux 等大小写敏感的系统，npm 源的 theme 必须使用shokax同时修改自定义配置文件为_config.shokax.yml
> 
> 没有说明_config.shokax.yml的来源

SXC在安装完成后会有提示（）

**Comment by FidStyle** [comment]
> > @zkz098 文档好像没写这部分的内容 原文描述是
> > 
> > > 更改根目录 /_config.yml 中的 theme 为 shokaX (SXC 默认 origin 或 npm 安装修改为 shokax)
> > > 请注意，本主题仅在 npm 上使用的是shokax,其他情况下均为shokaX
> > > 对于 linux 等大小写敏感的系统，npm 源的 theme 必须使用shokax同时修改自定义配置文件为_config.shokax.yml
> > 
> > 没有说明_config.shokax.yml的来源
> 
> SXC在安装完成后会有提示（）

我可能没看着()

**Comment by MoYuYuDe** [comment]
> > > 取消注释好了，没注意。谢谢了
> > 
> > 
> > 请问是取消哪里的注释啊? 我检查了 `_config.yml` 文件, 里面也没有关于 `hexo-lightning-minify` 的配置
> 
> 实际上配置在 https://docs.kaitaku.xyz/guide/config.html#%E6%96%87%E4%BB%B6%E5%8E%8B%E7%BC%A9 或者本项目README内也有配置模板，填入hexo根目录的_config.yml即可

明白了,谢谢大佬

**Comment by Patrick201hub** [comment]
> 取消注释好了，没注意。谢谢了

请问是取消哪个部分的注释呢

**Comment by FidStyle** [comment]
@Patrick201hub 应该是hexo-lightning-minify部分。完整config文件[官方文档](https://docs.kaitaku.xyz/guide/config.html#%E6%96%87%E4%BB%B6%E5%8E%8B%E7%BC%A9)配置文件

**Comment by Patrick201hub** [comment]
> @Patrick201hub 应该是hexo-lightning-minify部分。完整config文件参考github仓库的config配置文件

是添加到_config.yml文件的hexo-lightning-minify的配置部分吗，这里面要取消哪个注释呢？还是_config.shokax.yml文件里面的部分，但是这个文件我没有找到hexo-lightning-minify的部分

**Comment by FidStyle** [comment]
@Patrick201hub 看了一下，仓库_config没有这部分，需要自行添加，参考链接：
<https://docs.kaitaku.xyz/guide/config.html#文件压缩>

**Comment by Patrick201hub** [comment]
> @Patrick201hub 看了一下，仓库_config没有这部分，需要自行添加，参考链接： [https://docs.kaitaku.xyz/guide/config.html#文件压缩](https://docs.kaitaku.xyz/guide/config.html#%E6%96%87%E4%BB%B6%E5%8E%8B%E7%BC%A9)

添加之后要取消哪行的注释呢

**Comment by FidStyle** [comment]
没有，我当时是把这部分注释了，后面忘记取消注释了（）
原配置没问题
```
minify:
  js:
    enable: false # ShokaX 自带 esbuild 优化，不建议开启，其他主题建议开启
    exclude: # 排除文件，接受 string[]，需符合 micromatch 格式
  css:
    enable: true # 开启 CSS 优化
    options:
      targets: ">= 0.5%" # browserslist 格式的 target
    exclude: # 排除文件，接受 string[]，需符合 micromatch 格式
  html:
    enable: true # 开启 HTML 优化
    options:
      comments: false # 是否保留注释内容
    exclude: # 排除文件，接受 string[]，需符合 micromatch 格式
  image:
    enable: false # 开启图片预处理和自动 WebP 化
    options:
      avif: false
      webp: true # 预留配置项，现版本无作用
      quality: 80 # 质量，支持1-100的整数、lossless或nearLossless
      effort: 2 # CPU 工作量，0-6之间的整数(越低越快)
      replaceSrc: false # 自动替换生成html中的本地图片链接为webp链接
      # 我们更建议使用 Service Worker 来在用户侧实现 replaceSrc 的功能，这将能够以一种侵入式更小的方式实现链接替换
    exclude:

```
可以尝试重新配一下环境
